version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  build-app-karsajobs-ui:
    executor: docker/docker
    environtment:
      IMAGE_NAME: ghcr.io/yogypratama/karsajobs-ui
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Publish Docker Image to GitHub Container Registry
          command: 
            echo "$CR_PAT" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

workflows:
  ci:
    jobs:
      - docker/hadolint:
          dockerfiles: './Docke rfile'
      - build-app-karsajobs-ui:
          requires:
            - docker/hadolint